{{- if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "important-service.fullname" . }}
  labels:
    {{- include "important-service.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "important-service.selectorLabels" . | nindent 6 }}
  ingress:
    - toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
  egress:
    - toEntities:
        - kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
    {{- with .Values.ciliumNetworkPolicy.egressDomains }}
    - toFQDNs:
        {{- range . }}
        - matchPattern: {{ . | quote }}
        {{- end }}
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
    {{- end }}
{{- end }}
