image:
  registry: 'quay.io'
  name: 'giantswarm/helloworld'
  tag: 'latest'

resource:
  default:
    name: '{{ .Release.Name }}'

deployment:
  replicas: 1

hostname: helloworld.clusterid.k8s.installation.region.provider.gigantic.io

obtainTLSCertificate: false

ingressClassName: nginx
