version: 2.1

orbs:
  architect: giantswarm/architect@dev:3dc9a2b02103305fb2f6c0ddccdf34fdde6f24c4

workflows:
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-giantswarm-catalog
          context: architect
          executor: app-build-suite
          chart: hello-world
          app_catalog: giantswarm-catalog
          app_catalog_test: giantswarm-test-catalog
          persist_chart_archive: true
          filters:
            branches:
              ignore:
                - main
            tags:
              only: /^v.*/

      - architect/run-tests-with-ats:
          name: run-tests-with-ats
          requires:
            - push-to-giantswarm-catalog
          filters:
            branches:
              ignore:
                - main
            tags:
              only: /^v.*/
