version: 2.1

orbs:
  architect: giantswarm/architect@6.14.1

workflows:
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-catalog
          context: architect
          executor: app-build-suite
          chart: important-service
          app_catalog: giantswarm-playground-catalog
          app_catalog_test: giantswarm-playground-test-catalog
          persist_chart_archive: true
          #push_to_appcatalog: false
          filters:
            branches:
              ignore:
                - main
            tags:
              only: /^v.*/

      - architect/run-tests-with-ats:
          name: run-tests-with-ats
          requires:
            - push-to-catalog
          filters:
            branches:
              ignore:
                - main
            tags:
              only: /^v.*/
