apiVersion: v2
name: important-service
description: An application to demonstrate workload deployment at Giant Swarm
type: application
version: 0.2.2
appVersion: "0.3.0"
home: https://github.com/giantswarm/important-service
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
keywords:
  - demo
  - webapp
  - testing
sources:
  - https://github.com/giantswarm/helloworld
annotations:
  io.giantswarm.application.audience: all
  io.giantswarm.application.managed: "false"
  io.giantswarm.application.team: honeybadger
