{{- if .Values.ingress.enabled -}}
{{- if .Capabilities.APIVersions.Has "cilium.io/v2/CiliumNetworkPolicy" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
      {{- include "hello-world-app.labels" . | nindent 4 }}
  name: {{ include "hello-world-app.fullname" . }}
spec:
  egress:
    - {}
  ingress:
    - ports:
        - port: 8080
          protocol: TCP
  podSelector:
    matchLabels:
      {{- include "hello-world-app.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
{{- end }}
{{- end }}