apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hello-world-app.fullname" . }}
  labels:
    {{- include "hello-world-app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "hello-world-app.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - protocol: TCP
      port: 8080
