apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ tpl .Values.resource.default.name . }}-ClusterRole
  labels:
    app: {{ tpl .Values.resource.default.name . }}
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ tpl .Values.resource.default.name . }}-psp
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ tpl .Values.resource.default.name . }}-ClusterRoleBinding
  labels:
    app: {{ tpl .Values.resource.default.name . }}
subjects:
  - kind: ServiceAccount
    name: {{ tpl .Values.resource.default.name . }}-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: {{ tpl .Values.resource.default.name . }}-ClusterRole
  apiGroup: rbac.authorization.k8s.io