---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hello-world-app.fullname" . }}-psp
  labels:
    {{- include "hello-world-app.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ include "hello-world-app.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hello-world-app.fullname" . }}-psp
  labels:
    {{- include "hello-world-app.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hello-world-app.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "hello-world-app.fullname" . }}-psp
  apiGroup: rbac.authorization.k8s.io
