{{- if and (semverCompare "<1.25.0-0" .Capabilities.KubeVersion.Version) (not (((.Values.global).podSecurityStandards).enforced)) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hello-world.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "hello-world.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
