# yaml-language-server: $schema=../values.schema.json

heartbeat:
  # HTTPS is expected to fail in CI, as the alpine CA certificates don't include what example.com is using.
  url: https://www.example.com/
