# yaml-language-server: $schema=../values.schema.json

secretKey:
  value: dummy-secret-key-for-testing
heartbeat:
  url: https://www.example.com/
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
