name: Publish TechDocs
on:
  push:
    paths:
      - 'README.md'
      - 'docs/**' # markdown or any images in docs
      - 'helm/**/README.md'
      - '.github/workflows/**' # TODO: delete
    branches:
      - main
      - add-techdocs-workflow
  workflow_dispatch: {}

jobs:
  publish:
    uses: giantswarm/workflows-public/.github/workflows/publish-techdocs.yaml@e8fceba97eb03b9c603e86f041de2dab0ca7f5ad
