name: Publish TechDocs

on:
  push:
    branches:
      - main
      - master

jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22'
      - name: Install techdocs-cli
        run: npm install -g @techdocs/cli
      - name: Render TechDocs
        run: techdocs-cli --help
