name: Publish TechDocs
on:
  push:
    branches:
      - main
      - add-techdocs-workflow
  workflow_dispatch: {}

jobs:
  publish:
    uses: giantswarm/github/.github/workflows/publish-techdocs.yaml@add-techdocs-workflow
