name: Publish TechDocs
on:
  push:
    paths:
      - 'README.md'
      - 'docs/**' # markdown or any images in docs
      - 'helm/**/README.md'
      - '.github/workflows/**' # TODO: delete
    branches:
      - main
      - add-techdocs-workflow
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: giantswarm/workflows-public/.github/workflows/publish-techdocs.yaml@cdf133f7b248b96455a199e00c6d9fd7a4496e83
        with:
          aws_access_key_id: ${{ secrets.TECHDOCS_S3_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.TECHDOCS_S3_SECRET_ACCESS_KEY }}
