name: Publish TechDocs

on:
  push:
    branches:
      - main
      - master
      - add-techdocs-workflow # TODO: delete

jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22'

      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        env:
          cache-name: cache-node-modules
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          path:
            ./node_modules
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
      
      - name: Install techdocs-cli
        run: npm install @techdocs/cli
      
      - name: Find techdocs-cli
        run: |
          env | sort
          pwd
          find . -name techdocs-cli -type f

      - name: Show techdocs-cli version
        run: ./node_modules/@techdocs/cli/bin/techdocs-cli --version

      - name: Clone source repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Generate documentation
        run: |
          $GITHUB_WORKSPACE/node_modules/@techdocs/cli/bin/techdocs-cli \
            generate --output-dir=./tmp-docs-output
      
      - name: Show output
        run: ls -la ./tmp-docs-output
      
      - name: Publish
        if: ${{ github.event.repository.name != '' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TECHDOCS_PUBLISH_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TECHDOCS_PUBLISH_SECRET_KEY }}
          AWS_REGION: eu-central-1
        run: |
          $GITHUB_WORKSPACE/node_modules/@techdocs/cli/bin/techdocs-cli publish \
            --publisher-type awsS3 \
            --storage-name gs-backstage-techdocs-public \
            --entity default/component/${{ github.event.repository.name }} \
            --directory ./tmp-docs-output
