name: 'Push to App Catalog'

on: push

jobs:
  push_to_app_catalog:
    name: Push to app catalog
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout app repository
        uses: actions/checkout@v2

      - name: Checkout app catalog repository
        uses: actions/checkout@v2
        with:
          repository: rossf7/example-catalog
          path: app_catalog
          token: ${{ secrets.PAT }}

      - name: Setup Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2

      - name: Execute app-build-suite
        uses: docker://quay.io/giantswarm/app-build-suite:1.0.4
        with:
          args: --chart-dir helm/hello-world-app --catalog-base-url "https://rossf7.github.io/example-catalog/" --destination app_catalog

      - name: Update Helm index.yaml
        run:  |
          cd app_catalog
          ls -1
          helm repo index --url https://rossf7.github.io/example-catalog/
          ls -1
