name: 'Push to App Catalog'

jobs:
  steps:
    - name: Install app-build-suite
      uses: giantswarm/install-binary-action@v1.0.0
      with:
        binary: "app-build-suite"
        version: "1.0.4"
    - name: Checkout
      uses: actions/checkout@v2
