name: 'Push to App Catalog'

on:
  push:
    tags:
      - 'v*'

jobs:
  push_to_app_catalog:
    uses: giantswarm/app-build-suite/.github/workflows/push-to-app-catalog.yaml@github-action
    with:
      app_catalog: example-catalog
      chart: hello-world-app
      organization: rossf7
    secrets:
      envPAT: ${{ secrets.PAT }}
