name: 'Push to App Catalog'

on: push

jobs:
  push_to_app_catalog:
    name: Push to app catalog
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2

      - name: Clone app catalog repository
        run:  git clone -q --depth=1 --single-branch -b main "git@github.com:rossf7/example-catalog.git" example-catalog

      - name: Execute app-build-suite
        uses: docker://quay.io/giantswarm/app-build-suite:1.0.4
        with:
          args: --chart-dir helm/hello-world-app --catalog-base-url "https://rossf7.github.io/example-catalog/"
