name: 'Push to App Catalog'

on: push

jobs:
  push_to_app_catalog:
    name: Push to app catalog
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Execute ABS tool
        uses: docker://quay.io/giantswarm/app-build-suite:1.0.4
        with:
          args: -c helm/hello-world-app
